ENT.Base 			= "npc_vj_hlr2_antlion_guard"
ENT.Type 			= "ai"
ENT.PrintName 		= "Antlion Guardian"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Category		= "Half-Life 2"