ENT.Base 			= "npc_vj_hlr2_headcrab"
ENT.Type 			= "ai"
ENT.PrintName 		= "Headcrab"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Category		= "Half-Life 2"