ENT.Base 			= "npc_vj_hlr2_zombie_fast"
ENT.Type 			= "ai"
ENT.PrintName 		= "Fast Zombie"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Half-Life 2"